workflows:
  build-web-and-deploy:
    name: Build Web & Deploy to Firebase
    max_build_duration: 20
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      groups:
        - firebase-deploy
    scripts:
      - name: Clean old builds
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Build web release
        script: flutter build web --release

      - name: Deploy to Firebase Hosting
        script: |
          npx firebase deploy --only hosting --project workshop-mock-services --token $FIREBASE_TOKEN

    artifacts:
      - build/web
